name: publish

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      USERNAME: 'pmbanugo'
      IMG_NAME: 'csv-writer'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set App Name
        run: 'echo "IMG_NAME=$(echo ${USERNAME})/$(echo ${IMG_NAME})" >> $GITHUB_ENV'
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pack Build
        uses: dfreilich/pack-action@v2.0.0
        with:
          args: 'build ${{ env.IMG_NAME }} --builder paketobuildpacks/builder:base --publish'
